### PR TITLE
Support legacy create asset servlet (take 2)

### LINKED ISSUE #131: Support legacy create asset servlet (i.e. non-cloud service instances)
### Expected Behaviour

AEM Desktop (a consumer of this library) supports AEM instances all the way back to 6.4. This version of AEM doesn't include direct binary access, so asset uploads are done using the create asset servlet. This servlet supports uploading in parts, but acts as a more "standard" POST-like endpoint, where requests sent to it include a binary's data in the body.

The desktop app supports this by maintaining two "modes":

* Mode 1 is active against AEM instances that have direct binary access enabled, and uses this library to transfer local binaries to AEM.
* Mode 2 is active when direct binary access is _not_ enabled, and uses a less efficient, home-grown solution for uploading to the create asset servlet.

Upon revisiting mode 2, I started wondering how intrusive it would be to support the create asset servlet with this module. After some analysis and prototyping, I discovered that it was minimally intrusive, and actually fairly simple to extend the transfer process to support the create asset servlet.

By including this feature here, we can greatly simplify a lot of the desktop app's code, because we can entirely remove mode 2 and centralize on using this library for uploading assets to AEM, no matter the version.

### Actual Behaviour

This library only works with AEM instances that are configured with direct binary access.

### Reproduce Scenario (including but not limited to)

Attempting to use this library to upload assets to an AEM instance that doesn't have direct binary access enabled.

#### Steps to Reproduce

Attempt to use `AEMUpload` to upload assets to an AEM instance without direct binary access enabled. Note that the upload fails with an error.

#### Platform and Version

Reproducible on any platform or version.

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

### PR DESCRIPTION
**Pull request by mfrisbey**
## Description

This is a continuation of #132.

See linked issue for more context, but I discovered that it wasn't super difficult for this library to work with the old create asset servlet. By supporting this, we can update aem-upload so that it can upload binaries to any version of AEM. This will trickle down to AEM Desktop and allow us to remove quite a bit of legacy code.

In summary, here is what this PR does:

* Does some cleanup of `AEMUpload`:
  * Move most of its logic into a new class, `AEMBinaryUpload`. 
  * Adds a new class, `CreateAssetServletUpload`, which inherits from `AEMBinaryUpload`; the new upload process uses the create asset servlet instead of the direct binary upload algorithm.
  * `AEMUpload` will check whether direct binary access is enabled on the target AEM instance. If so, it will use `AEMBinaryUpload` to transfer the assets. If not, it will use `CreateAssetServletUpload`. This happens automatically, so there is no action required on the part of the consumer to decide which upload method to use.
* Adds a couple new methods to `TransferPart` and `TransferProcess` that allow new child classes to override behavior in a couple of key areas. This allows the transfer step that normally goes to Azure URLs to work with the create asset servlet, too.
* Adds unit tests for the new classes.
* Adds new e2e tests for verifying uploading with the create asset servlet. This does change the e2e tests so that they require two AEM environments: one with direct binary access enabled, and one without.

One thing to note is that concurrency doesn't work well with the create asset servlet, so even though the transfer process will still break a file into parts, the parts will always be uploaded sequentially to the create asset servlet.

Fixes #131 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mfrisbey** [comment]
@tmathern This PR contains your feedback from the other one. I did some refactoring of `AEMUpload` to reduce the amount of code duplication. It does mean more classes and some inheritance, as well as more intrusive changes to the existing binary upload. So it's more risky.

I also added auto-detection, so there's no change from a consumer's perspective, and no need for a user to know which type of upload to use.

**Review by bobvanmanen — CHANGES_REQUESTED** [review]
@mfrisbey I think this is a great initiative! I do have some feedback on the approach and to potentially simplify the implementation.

The two key differences I gather from the code when using the create asset servlet are:

* The pipeline is different
* The contents of what needs to be sent to the create asset servlet is different

The pipeline is something that is created at the top-level of the call stack, it makes sense to have 2 different implementations here however I would prefer that `CreateAssetServletUpload` and `AEMBinaryUpload` use a common (abstract) base class so it's clear what the differences are and avoid potential future changes to `AEMBinaryUpload` for AEM-CS upload to negatively impact `CreateAssetServletUpload`.

In order to accomplish the second point, there are number of hooks introduced in order to indirectly change the body of the HTTP request to the servlet. You have to follow each hook to understand what's happening.

I think a more direct approach, by creating adding an option to the `Transfer` function that indicates whether to send the raw binary or the "createassetservlet" form, and then create a separate instance of the upload path https://github.com/adobe/node-httptransfer/blob/create-asset-servlet/lib/functions/transfer.js#L80-L121 that is focused on createassetservlet would be easier to understand.

Common code between the paths can be moved in to functions but it gives you the flexibility to adjust the HTTP request directly rather than indirectly. It also avoids the specializations of classes just to add a different hook implementation.

**Comment by mfrisbey** [comment]
@bobvanmanen Thanks for the feedback. I'm happy to take another look, but my concern is that I've been trying to get this merged for over a month, and your suggestions don't seem trivial. If I go in and refactor this, can I have a commitment from you that we can get reviews turned around in a timely fashion? If not, I'd propose that we merge this as it is (since it works), and create follow-up issues to refactor some of it. The urgency for getting this merged is growing, and I need to know that we'll be able to get it pushed through quickly.

**Comment by bobvanmanen** [comment]
@mfrisbey I'll approve it with those changes.

**Comment by mfrisbey** [comment]
@bobvanmanen I've made another pass - will you please take a look? In summary:

* Created a new class, `AemBinaryUpload`, which serves as a common base class for `DirectBinaryUpload` and `CreateAssetServletUpload`. The abstract class contains a few methods that each child class must override to provide upload functionality.
* Added new class `HttpRequestGenerator`, which is now required in the constructor of `Transfer`. Also added two new classes that implement this abstract class: `BlockRequestGenerator` and `CreateAssetServletRequestGenerator`. `Transfer` uses the request generator to create the HTTP body and HTTP headers that should be used when transferring parts with HTTP. The block generator sends the part's raw binary as the request body, and the create asset servlet generator sends the form required by the create asset servlet.

Please let me know if this helps simplify the approach.

**Review by bobvanmanen — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
